id = "wx"
name = "WX"
version = "0.0.1"
schema_version = 1
authors = ["Artem Melnyk"]
description = "WX language support: syntax highlighting and LSP diagnostics, completions, and formatting"
repository = "https://github.com/wxlanguage/zed"

[grammars.wx]
repository = "https://github.com/wxlanguage/zed"
rev = "76575be14a5d639ed101b659eaeddba066922dd0"
path = "grammar"

[language_servers.wx]
name = "WX Language Server"
languages = ["WX"]
